### ISSUE TITLE
React Native demo implementation

### ISSUE THREAD

**Issue by 0xarthurxyz** [celo-org/SocialConnect#58]
@therealharpaljadeja's React Native demo currently lives at: https://github.com/therealharpaljadeja/socialconnect_rn_demo

- [x] Add README
- [x] Fork into celo-org/
- [x] Rename "SocialConnect-ReactNative-demo"

**Comment by 0xarthurxyz** [comment]
Meeting Wed, Feb 8

**Comment by therealharpaljadeja** [comment]
can we add the example to the docs readme?
